default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  password:
  host: database
  pool: 5
  port: 5432

development:
  <<: *default
  database: todo_database_development

test:
  <<: *default
  database: todo_database_test

production:
  <<: *default
  database: todo_database_production